#!/bin/sh
# Build/probe OpenBCM Linux BDE modules for the Redstone Linux 5.10 path.

set -eu

TOPDIR="$(cd "$(dirname "$0")/.." && pwd)"

OPENBCM_VERSION="${OPENBCM_VERSION:-6.5.27}"
OPENBCM_WORKDIR="${OPENBCM_WORKDIR:-$TOPDIR/build/openbcm}"
OPENBCM_TREE="${OPENBCM_TREE:-$OPENBCM_WORKDIR/OpenBCM}"
OPENBCM_SDK="${OPENBCM_SDK:-$OPENBCM_TREE/sdk-$OPENBCM_VERSION}"
OPENBCM_TARGET="${OPENBCM_TARGET:-linux-redstone-5_10}"
OPENBCM_BDE_OUT="${OPENBCM_BDE_OUT:-$OPENBCM_WORKDIR/redstone-bde}"
OPENBCM_BDE_BUNDLE="${OPENBCM_BDE_BUNDLE:-$TOPDIR/output/openbcm-bde}"

REDSTONE_KERNEL_DIR="${REDSTONE_KERNEL_DIR:-$TOPDIR/build/linux-5.10.224}"
ARCH="${ARCH:-powerpc}"
CROSS_COMPILE="${CROSS_COMPILE:-powerpc-linux-gnu-}"
MAKE="${MAKE:-make}"
FAILURES=0

usage() {
    cat <<EOF
Usage: $0 <command>

Commands:
  check      Check the OpenBCM source, Redstone kernel tree, and toolchain
  kernel     Build linux-kernel-bde.ko for Redstone Linux 5.10
  user       Build linux-user-bde.ko for Redstone Linux 5.10
  all        Build both BDE modules, kernel first
  bundle     Copy built BDE modules into a hardware-load bundle
  print-env  Print the resolved build paths
  clean      Remove generated OpenBCM BDE build outputs, bundle, and target file

Environment overrides:
  OPENBCM_VERSION=$OPENBCM_VERSION
  OPENBCM_WORKDIR=$OPENBCM_WORKDIR
  OPENBCM_SDK=$OPENBCM_SDK
  OPENBCM_TARGET=$OPENBCM_TARGET
  OPENBCM_BDE_OUT=$OPENBCM_BDE_OUT
  OPENBCM_BDE_BUNDLE=$OPENBCM_BDE_BUNDLE
  REDSTONE_KERNEL_DIR=$REDSTONE_KERNEL_DIR
  ARCH=$ARCH
  CROSS_COMPILE=$CROSS_COMPILE
EOF
}

ok() {
    printf 'ok: %s\n' "$*"
}

fail() {
    FAILURES=$((FAILURES + 1))
    printf 'fail: %s\n' "$*" >&2
}

die() {
    printf 'ERROR: %s\n' "$*" >&2
    exit 1
}

need_cmd() {
    command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

shell_quote() {
    printf "'"
    printf "%s" "$1" | sed "s/'/'\\\\''/g"
    printf "'"
}

print_var() {
    name=$1
    eval "value=\${$name}"
    printf '%s=' "$name"
    shell_quote "$value"
    printf '\n'
}

target_file() {
    printf '%s/make/Makefile.%s\n' "$OPENBCM_SDK" "$OPENBCM_TARGET"
}

check_file() {
    check_desc=$1
    check_path=$2

    if [ -f "$check_path" ]; then
        ok "$check_desc"
    else
        fail "$check_desc"
    fi
}

require_file() {
    check_desc=$1
    check_path=$2

    if [ -f "$check_path" ]; then
        ok "$check_desc"
    else
        die "$check_desc missing: $check_path"
    fi
}

check_dir() {
    check_desc=$1
    check_path=$2

    if [ -d "$check_path" ]; then
        ok "$check_desc"
    else
        fail "$check_desc"
    fi
}

write_target() {
    file=$(target_file)

    mkdir -p "$(dirname "$file")"
    {
        printf '%s\n' '# Generated by scripts/build-openbcm-bde.sh. Do not edit in place.'
        printf 'KERNDIR ?= %s\n' "$REDSTONE_KERNEL_DIR"
        printf '%s\n' 'KERNBLDDIR ?= $(KERNDIR)'
        printf 'CROSS_COMPILE ?= %s\n' "$CROSS_COMPILE"
        printf 'ARCH = %s\n' "$ARCH"
        printf '%s\n' 'TARGET_ARCHITECTURE = powerpc-linux-gnu'
        printf '%s\n' 'TOOLS_DIR ?= /usr/bin'
        printf '%s\n' 'SYSINC ?= $(shell $(CROSS_COMPILE)gcc -print-file-name=include)'
        printf '%s\n' 'LINUX_INCLUDE ?= $(KERNDIR)/include'
        printf '%s\n' 'KBUILD_VERBOSE ?= 1'
        printf '%s\n' 'export ARCH CROSS_COMPILE KBUILD_VERBOSE'
        printf '%s\n' 'export KCFLAGS += -Wno-error'
        printf '%s\n' 'BCM_CFLAGS = -Wall'
        printf '%s\n' 'KERNEL_INCLUDE_FLAGS := -I$(KERNDIR)/include'
        printf '%s\n' 'KERNEL_INCLUDE_FLAGS += -I$(KERNDIR)/arch/$(ARCH)/include'
        printf '%s\n' 'KERNEL_INCLUDE_FLAGS += -I$(KERNDIR)/arch/$(ARCH)/include/generated'
        printf '%s\n' 'KERNEL_INCLUDE_FLAGS += -I$(KERNDIR)/include/generated'
        printf '%s\n' 'KERNEL_INCLUDE_FLAGS += -I$(KERNDIR)/arch/$(ARCH)/include/uapi'
        printf '%s\n' 'KERNEL_INCLUDE_FLAGS += -I$(KERNDIR)/arch/$(ARCH)/include/generated/uapi'
        printf '%s\n' 'KERNEL_INCLUDE_FLAGS += -I$(KERNDIR)/include/uapi'
        printf '%s\n' 'KERNEL_INCLUDE_FLAGS += -I$(KERNDIR)/include/generated/uapi'
        printf '%s\n' 'KFLAGS ?= -nostdinc -isystem $(SYSINC) $(KERNEL_INCLUDE_FLAGS)'
        printf '%s\n' 'KFLAGS += -include $(KERNDIR)/include/generated/autoconf.h'
        printf '%s\n' 'KFLAGS += -include $(KERNDIR)/include/linux/compiler_types.h'
        printf '%s\n' 'KFLAGS += -D__KERNEL__ -DMODULE -DNDEBUG'
        printf '%s\n' 'KFLAGS += -Wundef -Wstrict-prototypes -Wno-trigraphs'
        printf '%s\n' 'KFLAGS += -fno-strict-aliasing -fno-common -fno-delete-null-pointer-checks'
        printf '%s\n' 'KFLAGS += -Wno-format-security -Wno-sign-compare'
        printf '%s\n' 'KFLAGS += -Wdeclaration-after-statement -Wno-pointer-sign'
        printf '%s\n' 'KFLAGS += -Wno-error'
        printf '%s\n' 'CFLAGS += -DUSE_LINUX_BDE_MMAP=1'
        printf '%s\n' 'CFLAGS += -Wno-error -Wno-pointer-to-int-cast -Wno-int-to-pointer-cast'
        printf '%s\n' 'CFLAGS += -Wno-error=unused-function -Wno-error=unused-variable'
        printf '%s\n' 'CFLAGS += -Wno-error=unused-but-set-variable -Wno-error=maybe-uninitialized'
        printf '%s\n' 'CFLAGS += -Wno-error=array-bounds -Wno-error=strict-overflow'
        printf '%s\n' 'CFLAGS += -Wno-error=sizeof-pointer-div -Wno-error=uninitialized'
        printf '%s\n' 'CFLAGS += -Wno-error=format-overflow -Wno-error=address-of-packed-member'
        printf '%s\n' 'CFLAGS += -Wno-stringop-overflow -Wno-stringop-truncation'
        printf '%s\n' 'CFLAGS += -Wno-deprecated-declarations -fcommon'
        printf '%s\n' 'CFGFLAGS += -fgnu89-inline'
        printf '%s\n' 'CFGFLAGS += -DSYS_BE_PIO=1 -DSYS_BE_PACKET=1 -DSYS_BE_OTHER=1'
        printf '%s\n' 'CFGFLAGS += -DBE_HOST=1'
        printf '%s\n' 'CFGFLAGS += -DBCM_PLATFORM_STRING=\"REDSTONE_PPC\"'
        printf '%s\n' 'CFGFLAGS += -DSAL_BDE_DMA_MEM_DEFAULT=32'
        printf '%s\n' 'ifneq ($(targetplat),user)'
        printf '%s\n' 'include ${SDK}/make/Makefile.linux-kernel-2_6'
        printf '%s\n' 'endif'
    } > "$file"

    ok "generated OpenBCM target file: $file"
}

check_inputs() {
    need_cmd "$MAKE"
    need_cmd "${CROSS_COMPILE}gcc"
    need_cmd "${CROSS_COMPILE}ld"

    sh "$TOPDIR/scripts/prepare-openbcm.sh" check

    check_dir "OpenBCM SDK directory exists: $OPENBCM_SDK" "$OPENBCM_SDK"
    check_file "OpenBCM kernel BDE Makefile exists" \
        "$OPENBCM_SDK/systems/bde/linux/kernel/Makefile"
    check_file "OpenBCM user BDE Makefile exists" \
        "$OPENBCM_SDK/systems/bde/linux/user/kernel/Makefile"
    check_dir "Redstone Linux 5.10 build tree exists: $REDSTONE_KERNEL_DIR" \
        "$REDSTONE_KERNEL_DIR"
    check_file "Redstone kernel .config exists" "$REDSTONE_KERNEL_DIR/.config"
    check_file "Redstone kernel Module.symvers exists" "$REDSTONE_KERNEL_DIR/Module.symvers"
    check_file "Redstone kernel autoconf.h exists" \
        "$REDSTONE_KERNEL_DIR/include/generated/autoconf.h"

    write_target
    check_file "generated OpenBCM Redstone target exists" "$(target_file)"

    if [ "$FAILURES" -ne 0 ]; then
        printf 'OpenBCM BDE build preflight failed: %s failure(s)\n' "$FAILURES" >&2
        exit 1
    fi

    printf 'OpenBCM BDE build preflight passed\n'
}

reset_module_dir() {
    module_name=$1
    module_dir="$OPENBCM_BDE_OUT/$module_name-src"

    mkdir -p "$OPENBCM_BDE_OUT"
    rm -rf "$module_dir"
    mkdir -p "$module_dir"
    printf '%s\n' "$module_dir"
}

copy_module_sources() {
    module_dir=$1
    shift

    for source_file in "$@"; do
        cp "$source_file" "$module_dir/"
    done
}

write_module_makefile() {
    module_dir=$1
    module_name=$2
    module_objects=$3

    {
        printf 'obj-m := %s.o\n' "$module_name"
        printf '%s-y := %s\n' "$module_name" "$module_objects"
        printf 'SDK := %s\n' "$OPENBCM_SDK"
        printf '%s\n' 'ccflags-y += -I$(src)'
        printf '%s\n' 'ccflags-y += -I$(SDK)/include'
        printf '%s\n' 'ccflags-y += -I$(SDK)/systems/linux/kernel/modules/include'
        printf '%s\n' 'ccflags-y += -I$(SDK)/systems/bde/linux/include'
        printf '%s\n' 'ccflags-y += -I$(SDK)/systems/bde/shared/include'
        printf '%s\n' 'ccflags-y += -I$(SDK)/systems/bde/linux/shared/include'
        printf '%s\n' 'ccflags-y += -DUSE_LINUX_BDE_MMAP=1'
        printf '%s\n' 'ccflags-y += -DSYS_BE_PIO=1 -DSYS_BE_PACKET=1 -DSYS_BE_OTHER=1'
        printf '%s\n' 'ccflags-y += -DBE_HOST=1'
        printf '%s\n' 'ccflags-y += -DBCM_PLATFORM_STRING=\"REDSTONE_PPC\"'
        printf '%s\n' 'ccflags-y += -DSAL_BDE_DMA_MEM_DEFAULT=32'
        printf '%s\n' 'ccflags-y += -Wno-error'
        printf '%s\n' 'ccflags-y += -Wno-pointer-to-int-cast -Wno-int-to-pointer-cast'
        printf '%s\n' 'ccflags-y += -Wno-unused-function -Wno-unused-variable'
        printf '%s\n' 'ccflags-y += -Wno-unused-but-set-variable -Wno-maybe-uninitialized'
        printf '%s\n' 'ccflags-y += -Wno-array-bounds -Wno-strict-overflow'
        printf '%s\n' 'ccflags-y += -Wno-sizeof-pointer-div -Wno-uninitialized'
        printf '%s\n' 'ccflags-y += -Wno-format-overflow -Wno-address-of-packed-member'
        printf '%s\n' 'ccflags-y += -Wno-stringop-overflow -Wno-stringop-truncation'
        printf '%s\n' 'ccflags-y += -Wno-deprecated-declarations -fcommon'
    } > "$module_dir/Makefile"
}

run_kbuild() {
    module_dir=$1
    module_name=$2
    extra_symbols=${3:-}

    if [ -n "$extra_symbols" ]; then
        "$MAKE" -C "$REDSTONE_KERNEL_DIR" M="$module_dir" \
            KBUILD_EXTRA_SYMBOLS="$extra_symbols" \
            ARCH="$ARCH" \
            CROSS_COMPILE="$CROSS_COMPILE" \
            LD="${CROSS_COMPILE}ld" \
            KCFLAGS="-Wno-error" \
            modules
    else
        "$MAKE" -C "$REDSTONE_KERNEL_DIR" M="$module_dir" \
            ARCH="$ARCH" \
            CROSS_COMPILE="$CROSS_COMPILE" \
            LD="${CROSS_COMPILE}ld" \
            KCFLAGS="-Wno-error" \
            modules
    fi

    if [ -f "$module_dir/$module_name.ko" ]; then
        cp "$module_dir/$module_name.ko" "$OPENBCM_BDE_OUT/$module_name.ko"
        ok "built $OPENBCM_BDE_OUT/$module_name.ko"
    else
        die "expected output missing: $module_dir/$module_name.ko"
    fi
}

build_kernel_bde() {
    check_inputs
    module_dir=$(reset_module_dir "linux-kernel-bde")

    copy_module_sources "$module_dir" \
        "$OPENBCM_SDK/systems/bde/linux/kernel/linux_shbde.c" \
        "$OPENBCM_SDK/systems/bde/linux/kernel/linux_dma.c" \
        "$OPENBCM_SDK/systems/bde/linux/kernel/linux-kernel-bde.c" \
        "$OPENBCM_SDK/systems/bde/linux/kernel/linux_shbde.h" \
        "$OPENBCM_SDK/systems/bde/linux/shared/mpool.c" \
        "$OPENBCM_SDK/systems/bde/shared/shbde_pci.c" \
        "$OPENBCM_SDK/systems/bde/shared/shbde_iproc.c" \
        "$OPENBCM_SDK/systems/bde/shared/shbde_mdio.c" \
        "$OPENBCM_SDK/systems/linux/kernel/modules/shared/gmodule.c"
    mv "$module_dir/linux-kernel-bde.c" "$module_dir/linux-kernel-bde-file.c"
    write_module_makefile "$module_dir" "linux-kernel-bde" \
        "linux_shbde.o linux_dma.o mpool.o linux-kernel-bde-file.o shbde_pci.o shbde_iproc.o shbde_mdio.o gmodule.o"

    printf '==> Building OpenBCM linux-kernel-bde.ko through Redstone Kbuild\n'
    run_kbuild "$module_dir" "linux-kernel-bde"
}

build_user_bde() {
    if [ ! -f "$OPENBCM_BDE_OUT/linux-kernel-bde-src/Module.symvers" ]; then
        die "linux-kernel-bde.ko must be built before linux-user-bde.ko"
    fi

    check_inputs
    module_dir=$(reset_module_dir "linux-user-bde")

    copy_module_sources "$module_dir" \
        "$OPENBCM_SDK/systems/bde/linux/user/kernel/linux-user-bde.c" \
        "$OPENBCM_SDK/systems/bde/linux/user/kernel/linux-user-bde.h" \
        "$OPENBCM_SDK/systems/linux/kernel/modules/shared/gmodule.c"
    mv "$module_dir/linux-user-bde.c" "$module_dir/linux-user-bde-file.c"
    write_module_makefile "$module_dir" "linux-user-bde" \
        "linux-user-bde-file.o gmodule.o"

    printf '==> Building OpenBCM linux-user-bde.ko through Redstone Kbuild\n'
    run_kbuild "$module_dir" "linux-user-bde" \
        "$OPENBCM_BDE_OUT/linux-kernel-bde-src/Module.symvers"
}

openbcm_head() {
    if command -v git >/dev/null 2>&1 && [ -d "$OPENBCM_TREE/.git" ]; then
        git -C "$OPENBCM_TREE" rev-parse HEAD 2>/dev/null || printf 'unknown'
    else
        printf 'unknown'
    fi
}

kernel_release() {
    if [ -f "$REDSTONE_KERNEL_DIR/include/config/kernel.release" ]; then
        cat "$REDSTONE_KERNEL_DIR/include/config/kernel.release"
    else
        printf 'unknown'
    fi
}

manifest_module() {
    module_path=$1
    module_name=$(basename "$module_path")

    printf '\n[module %s]\n' "$module_name"
    printf 'path=%s\n' "$module_path"
    printf 'bytes=%s\n' "$(wc -c < "$module_path" | tr -d ' ')"
    if command -v sha256sum >/dev/null 2>&1; then
        printf 'sha256='
        sha256sum "$module_path" | awk '{print $1}'
    fi
    if command -v file >/dev/null 2>&1; then
        printf 'file='
        file -b "$module_path"
    fi
    if command -v modinfo >/dev/null 2>&1; then
        vermagic=$(modinfo -F vermagic "$module_path" 2>/dev/null || true)
        if [ -n "$vermagic" ]; then
            printf 'vermagic=%s\n' "$vermagic"
        fi
    fi
}

bundle_bde() {
    kernel_module="$OPENBCM_BDE_OUT/linux-kernel-bde.ko"
    user_module="$OPENBCM_BDE_OUT/linux-user-bde.ko"
    manifest="$OPENBCM_BDE_BUNDLE/redstone-openbcm-bde.manifest"

    require_file "OpenBCM kernel BDE module exists" "$kernel_module"
    require_file "OpenBCM user BDE module exists" "$user_module"

    mkdir -p "$OPENBCM_BDE_BUNDLE"
    cp "$kernel_module" "$OPENBCM_BDE_BUNDLE/"
    cp "$user_module" "$OPENBCM_BDE_BUNDLE/"

    {
        printf 'redstone_openbcm_bde_bundle=1\n'
        printf 'openbcm_version=%s\n' "$OPENBCM_VERSION"
        printf 'openbcm_head=%s\n' "$(openbcm_head)"
        printf 'openbcm_sdk=%s\n' "$OPENBCM_SDK"
        printf 'openbcm_target=%s\n' "$OPENBCM_TARGET"
        printf 'redstone_kernel_dir=%s\n' "$REDSTONE_KERNEL_DIR"
        printf 'kernel_release=%s\n' "$(kernel_release)"
        printf 'arch=%s\n' "$ARCH"
        printf 'cross_compile=%s\n' "$CROSS_COMPILE"
        printf 'load_order=linux-kernel-bde.ko linux-user-bde.ko\n'
        printf 'hardware_smoke=insmod ./linux-kernel-bde.ko dma_size=4; insmod ./linux-user-bde.ko; ls -l /dev/linux-*-bde; lspci -nn | grep -i "14e4:b846"\n'
        manifest_module "$OPENBCM_BDE_BUNDLE/linux-kernel-bde.ko"
        manifest_module "$OPENBCM_BDE_BUNDLE/linux-user-bde.ko"
    } > "$manifest"

    ok "bundled OpenBCM BDE modules under $OPENBCM_BDE_BUNDLE"
    ok "wrote $manifest"
}

print_env() {
    print_var OPENBCM_VERSION
    print_var OPENBCM_WORKDIR
    print_var OPENBCM_TREE
    print_var OPENBCM_SDK
    print_var OPENBCM_TARGET
    print_var OPENBCM_BDE_OUT
    print_var OPENBCM_BDE_BUNDLE
    print_var REDSTONE_KERNEL_DIR
    print_var ARCH
    print_var CROSS_COMPILE
    print_var MAKE
    printf 'OPENBCM_TARGET_FILE='
    shell_quote "$(target_file)"
    printf '\n'
}

case "${1:-check}" in
    check)
        check_inputs
        ;;
    kernel)
        build_kernel_bde
        ;;
    user)
        build_user_bde
        ;;
    all)
        build_kernel_bde
        build_user_bde
        ;;
    bundle)
        bundle_bde
        ;;
    print-env)
        print_env
        ;;
    clean)
        rm -rf "$OPENBCM_BDE_OUT"
        rm -rf "$OPENBCM_BDE_BUNDLE"
        rm -f "$(target_file)"
        ok "removed OpenBCM BDE outputs"
        ;;
    -h|--help|help)
        usage
        ;;
    *)
        usage >&2
        exit 2
        ;;
esac
